### ISSUE TITLE
Unable to start after upgrade

### ISSUE THREAD

**Issue by qjiang888** [esphome/hassio#18]
400 Client Error for http+docker://localhost/v1.39/containers/5181f8a60c0a8d5ed8f42e9bc548a26ff9412c03002fe7515f235c1e89c4353d/start: Bad Request ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown")

**Comment by jesserockz** [comment]
Please open an issue on https://github.com/esphome/issues if this is still a problem
