### ISSUE TITLE
Add-on config 'auto_uart' is deprecated

### ISSUE THREAD

**Issue by yfands** [esphome/hassio#20]
I dont use even ESP Home (sorry) but my logfile is complaining:

21-02-15 12:06:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

Hassio  2021.2.3

Greetings Frank

**Comment by TheZoker** [comment]
This issue has already been addressed here:
https://github.com/esphome/issues/issues/1806

The issue came back, because the config.json file is generated by a template. 
That has been addressed here:
https://github.com/esphome/hassio/pull/19

**Comment by jesserockz** [comment]
Fixed in #19 and 1.16.2
